### PR TITLE
Fixed getting price scale position for series title

### LINKED ISSUE #463: Series label (title) is not visible when priceScaleId is set
**Lightweight Charts Version:** 3.0.0

**Steps/code to reproduce:**
Add a serie with title property and priceScaleId
```javascript
var lineSeries = chart.addLineSeries({
	priceScaleId: 'test',
	title: 'LINE LABEL' // not visible because priceScaleId
});
```

**Actual behavior:**
Title is not visible
image

**Expected behavior:**
.title is visible
image

**CodeSandbox/JSFiddle/etc link:**

https://jsfiddle.net/qja2t8pw/

### PR DESCRIPTION
**Pull request by timocov**
**Type of PR:** bugfix

**PR checklist:**

- [x] Addresses an existing issue: fixes #463
- [x] Includes tests
- [ ] Documentation update

### CODE REVIEW

File: src/views/pane/pane-price-axis-view.ts [hunk 1]
```diff
@@ -66,14 +66,13 @@ export class PanePriceAxisView implements IPaneView {
 			return null;
 		}
 
-		const priceScale = this._dataSource.priceScale();
+		const priceScale = pane.isOverlay(this._dataSource) ? pane.defaultPriceScale() : this._dataSource.priceScale();
```
Comment (kirchet) [inline src/views/pane/pane-price-axis-view.ts:69]: Maybe we should add a comment here that this price scale is used only to calculate label's position

Comment (timocov) [reply src/views/pane/pane-price-axis-view.ts:69]:
```suggestion
		// this price scale will be used to find label placement only (left, right, none)
		const priceScale = pane.isOverlay(this._dataSource) ? pane.defaultPriceScale() : this._dataSource.priceScale();
```

Sure
