### PR TITLE
Fixed bug in setVisibleRange

### LINKED ISSUE #33: setVisibleRange works incorrectly
Please check this [jsfiddle](https://jsfiddle.net/TradingView/8v02wao7/1/) it should display the chart from the beginning of 2019 (actually, from Dec, 26), but it displays it from the middle of Jan'2019.

### PR DESCRIPTION
**Pull request by eugene-korobko**
Bugfix: fixed setVisibleRange function

Fixes #33

**Overview of change:**

Apply new setVisibleRange in RAF like fitContent

### CODE REVIEW

File: src/model/time-scale.ts [hunk 1]
```diff
@@ -530,6 +530,25 @@ export class TimeScale {
...
+		}
+
+		const firstPoint = ensureNotNull(points.valueAt(firstIndex)).timestamp;
+		const lastPoint = ensureNotNull(points.valueAt(lastIndex)).timestamp;
+
+		const barRange = new BarsRange(
+			ensureNotNull(points.indexOf(Math.max(firstPoint, range.from.timestamp) as UTCTimestamp, true)),
+			ensureNotNull(points.indexOf(Math.min(lastPoint, range.to.timestamp) as UTCTimestamp, true))
+		);
+		this.setVisibleRange(barRange);
```
Comment (timocov) [inline src/model/time-scale.ts]: I would like to see graphics test case for that.

File: src/model/time-scale.ts [hunk 2]
```diff
@@ -512,7 +512,7 @@ export class TimeScale {
 	}
 
 	public setVisibleRange(range: BarsRange): void {
-		const length = range.lastBar() - range.firstBar();
+		const length = range.lastBar() - range.firstBar() + 1;
```
Comment (timocov) [inline src/model/time-scale.ts]:
```suggestion
		const length = range.count();
```

File: src/model/time-scale.ts (hunk 1 above)
Comment (eugene-korobko) [reply src/model/time-scale.ts]: I've added one
