### PR TITLE
Fixed unexpected base issue

### LINKED ISSUE #1951: "Unexpected base" exception
**Lightweight Charts™ Version:** 5.0.8

**Steps/code to reproduce:**

```js
const chart = LightweightCharts.createChart(document.body);
const lineSeries = chart.addSeries(LightweightCharts.LineSeries, {
  priceFormat: {
    type: "custom",
    formatter: (p) => `$${p}`,
    minMove: 1e-18,
  },
});
lineSeries.setData([
  { time: "2019-04-11", value: 1e-18 },
  { time: "2019-04-12", value: 2e-18 },
  { time: "2019-04-13", value: 3e-18 },
]);
```

**Actual behavior:**

The error "unexpected base" is thrown, the chart is empty

**Expected behavior:**

No errors are thrown, the chart is not empty

**CodeSandbox/JSFiddle/etc link:**

https://codesandbox.io/p/devbox/distracted-alex-nnh95t?workspaceId=ws_STqRXy5GvTDXv6UUWnmg4n

### PR DESCRIPTION
**Pull request by kirchet**
**Type of PR:**  bugfix
**PR checklist:**

- [x] Addresses an existing issue: fixes #1951
- [x] Includes tests
- [ ] Documentation update

**Overview of change:**

Added one additional option `base` to avoid calculation errors when we use `minMove`

### CODE REVIEW

**Comment by SlicedSilver** [comment]
Seems we are now getting errors in some of the existing test cases.
Examples:
```
priceFormat: {
	minMove: 1e-9,
	precision: 9,
},
```
```
priceFormat: {
	minMove: 0.00001,
	precision: 5,
},
```

**Comment by SlicedSilver** [comment]
The graphics tests (part 3) seemed to finish but not exit correctly. We could probably decrease the timeout limit from 20 minutes to 10 minutes:
https://github.com/tradingview/lightweight-charts/blob/7170ead5a941e08b6215afad36c56a2bdb5f5dde/.circleci/config.yml#L91

**Comment by kirchet** [comment]
> The graphics tests (part 3) seemed to finish but not exit correctly. We could probably decrease the timeout limit from 20 minutes to 10 minutes:
> 
> https://github.com/tradingview/lightweight-charts/blob/7170ead5a941e08b6215afad36c56a2bdb5f5dde/.circleci/config.yml#L91

Updated 91e6c4232b6433a8a1218e72f49630a80d668e97

File: tests/e2e/graphics/test-cases/series/series-price-formatter-extra-small-values.js [hunk 1]
```diff
@@ -0,0 +1,26 @@
...
+	return res;
+}
+
+function runTestCase(container) {
+	const chart = window.chart = LightweightCharts.createChart(container, { layout: { attributionLogo: false } });
+
+	const lineSeries = chart.addSeries(LightweightCharts.LineSeries, {
+		priceFormat: {
+			type: 'custom',
+			format: p => `$${p}`,
```
Comment (SlicedSilver) [inline tests/e2e/graphics/test-cases/series/series-price-formatter-extra-small-values.js:21]:
```suggestion
			formatter: p => `$${p}`,
```

File: .circleci/config.yml [hunk 2]
```diff
@@ -88,7 +88,7 @@ commands:
             echo 'export BRANCH_SPECIFIC_TEST=<< parameters.branchSpecificTest >>' >> $BASH_ENV
       - run:
           command: scripts/run-graphics-tests.sh
-          no_output_timeout: 20m
+          no_output_timeout: 10m
```
Comment (SlicedSilver) [inline .circleci/config.yml:91]: Seems this is a timeout after the last bit of output into the terminal. So we could probably decrease this further to `5m`

**Review by SlicedSilver — APPROVED** [review]
