### PR TITLE
Fixed bug with series.priceFormatter().format(price) #790

### LINKED ISSUE #790: series.priceFormatter().format(price) does not work
**Lightweight Charts Version:** 3.2.0

**Steps/code to reproduce:**

```js
const chart = LightweightCharts.createChart(document.body);
const lineSeries = chart.addLineSeries();
lineSeries.priceFormatter().format(123.4);
```

**Actual behavior:**

an error "Uncaught TypeError: chart.timeScale(...).formatDateTime is not a function" occurs

**Expected behavior:**

I will get the formatted price value

### PR DESCRIPTION
**Pull request by olegchernenko**
**Type of PR:** bugfix

**PR checklist:**

- [x] Addresses an existing issue: fixes #790 
- [x] Includes tests
- [ ] Documentation update

### CODE REVIEW

File: src/model/price-scale.ts [hunk 1]
```diff
@@ -659,7 +659,7 @@ export class PriceScale {
 		switch (this._options.mode) {
 			case PriceScaleMode.Percentage:
 			case PriceScaleMode.IndexedTo100:
-				return this.formatter().format(logical);
+				return this.formatter().format(logical as BarPrice);
```
Comment (timocov) [inline src/model/price-scale.ts:662]: it seems that we can revert it now

File: src/formatters/volume-formatter.ts [hunk 2]
```diff
@@ -1,6 +1,5 @@
-import { IFormatter } from './iformatter';
 
-export class VolumeFormatter implements IFormatter {
+export class VolumeFormatter {
```
Comment (timocov) [inline src/formatters/volume-formatter.ts:2]: it should implements IPriceFormatter

File: src/formatters/price-formatter.ts [hunk 3]
```diff
@@ -29,7 +27,7 @@ export function numberToStringWithLeadingZero(value: number, length: number): st
 	return (dummyString + value.toString()).slice(-length);
 }
 
-export class PriceFormatter implements IFormatter {
+export class PriceFormatter {
```
Comment (timocov) [inline src/formatters/price-formatter.ts:30]: it should implements IPriceFormatter

File: tests/e2e/graphics/test-cases/series/series-price-formatter.js [hunk 4]
```diff
@@ -0,0 +1,22 @@
+function runTestCase(container) {
+	const chart = LightweightCharts.createChart(container);
+
+	const lineSeries = chart.addLineSeries();
```
Comment (timocov) [inline tests/e2e/graphics/test-cases/series/series-price-formatter.js:4]: can you add at least 1 data point please? afaik the formatter might not be work if no data (e.g. because percentage formatter requires `firstValue`)

File: tests/e2e/graphics/test-cases/series/series-price-formatter.js [hunk 5]
```diff
@@ -0,0 +1,22 @@
...
+
+	lineSeries.applyOptions({
+		priceFormat: LightweightCharts.PriceScaleMode.Percentage,
+	});
+	lineSeries.priceFormatter().format(12.1);
+
+	lineSeries.applyOptions({
+		priceFormat: LightweightCharts.PriceScaleMode.IndexedTo100,
+	});
+	lineSeries.priceFormatter().format(12.1);
```
Comment (timocov) [inline tests/e2e/graphics/test-cases/series/series-price-formatter.js:21]: can you please also check the format of series: price, volume, custom.

**Review by timocov — CHANGES_REQUESTED** [review]

**Review by timocov — APPROVED** [review]
