### PR TITLE
Fixed last price animation on setting new data

### LINKED ISSUE #886: Last price animation is active when no data added to the right (but to the left)
**Lightweight Charts Version:**  3.7.0

**Steps/code to reproduce:**

* Enable last price animation on data update
* Add more history bars via `setData`

**Actual behavior:**

Animation is active

**Expected behavior:**

No animation. Animation should start only if a series has data and we're adding new bars to the right side or updating the last bar

**Screenshots:**

animation

**CodeSandbox/JSFiddle/etc link:**

https://jsfiddle.net/6hq2vopz/2/

### PR DESCRIPTION
**Pull request by kirchet**
**Type of PR:** 

**PR checklist:**

- [x] Addresses an existing issue: fixes #886
- [x] Includes tests
- [ ] Documentation update

**Overview of change:**

Fixed incorrect last price animation on first `setData` and adding new data to the left side

### CODE REVIEW

File: src/model/series.ts [hunk 1]
```diff
@@ -240,13 +240,24 @@ export class Series<T extends SeriesType = SeriesType> extends PriceDataSource i
 	}
 
 	public setData(data: readonly SeriesPlotRow<T>[]): void {
+		const lastIndex = this._data.lastIndex();
+		const newRealtimeDataReceived = lastIndex !== null && data.length > 0 && data[data.length - 1].index >= lastIndex;
```
Comment (timocov) [inline src/model/series.ts:244]: it is not really true - you could extend time scale in the middle, indexes will be changed, but no new data received.

Comment (kirchet) [reply src/model/series.ts:244]: Yes, and in this case we should display last price animation for this series. BTW, maybe name is not so clear and correct

Comment (timocov) [reply src/model/series.ts:244]: > and in this case we should display last price animation for this series

Why? Nothing is changed...

Comment (kirchet) [reply src/model/series.ts:244]: Hm, so we need to compare times? Not indexes?

Comment (timocov) [reply src/model/series.ts:244]: Yeah, I think so. Btw we already did this [in updating time scale](https://github.com/tradingview/lightweight-charts/blob/ebd3586cd7334b9a251cb7ea2e16d5308166d3c2/src/model/chart-model.ts#L560-L589).

But most likely we need to provide an index of the first changed point for every series (or for being updated one) and rely on this index. https://github.com/tradingview/lightweight-charts/issues/886#issuecomment-966274225

Also, please keep in mind that it is possible that an array _could be_ shared between data layer and series due perf optimizations (that's why a data array is `readonly`).

Comment (kirchet) [reply src/model/series.ts:244]: We can just change the current condition to compare times instead of indexes, I think that tha's more easiest way to do the same work.

Comment (kirchet) [reply src/model/series.ts]: https://github.com/tradingview/lightweight-charts/pull/892/commits/12c227b2cfb18b84801853f3f50b20aefe180f0c

File: tests/e2e/graphics/test-cases/series/no-last-price-animation-on-first-set-data-after-reseting-data.js [hunk 2]
```diff
@@ -0,0 +1,23 @@
...
+	series.setData([]);
+
+	series.setData([
+		{ time: '1990-04-24', value: 0 },
+		{ time: '1990-04-25', value: 1 },
+		{ time: '1990-04-26', value: 2 },
+		{ time: '1990-04-28', value: 3 },
+	]);
+
+	return new Promise(resolve => setTimeout(resolve, 500));
```
Comment (timocov) [inline tests/e2e/graphics/test-cases/series/no-last-price-animation-on-first-set-data-after-reseting-data.js:22]: what value should be here? 500 means we want to handle after animation time or somewhere in the middle?

File: src/api/data-layer.ts [hunk 3]
```diff
@@ -277,9 +307,11 @@ export class DataLayer {
 
 		this._updateLastSeriesRow(series, plotRow);
 
+		const info: SeriesUpdateInfo = { lastBarUpdatedOrNewBarsAddedToTheRight: true };
```
Comment (timocov) [inline src/api/data-layer.ts:310]: it is not really true. what if you replace the last item with whitespace? time scale won't be affected, no new data added, but animation will be started?

File: src/api/data-layer.ts [hunk 4]
```diff
@@ -155,6 +159,26 @@ function createEmptyTimePointData(timePoint: TimePoint): TimePointData {
...
+	}
+
+	return seriesRows.length > 0 ? seriesRows[seriesRows.length - 1].time.timestamp : undefined;
+}
+
+function seriesUpdateInfo(seriesRows: SeriesPlotRow[] | undefined, prevSeriesRows: SeriesPlotRow[] | undefined): SeriesUpdateInfo | undefined {
+	const lastTime = seriesRowsLastTime(seriesRows);
+	if (lastTime !== undefined) {
+		const prevLastTime = seriesRowsLastTime(prevSeriesRows);
+		if (prevLastTime !== undefined && lastTime >= prevLastTime) {
```
Comment (timocov) [inline src/api/data-layer.ts:174]: `lastTime >= prevLastTime` does this mean that if you scroll to the left (to the past) and you'll set data for the whole period this animation will be run as well even nothing is changed for the last bar?

File: tests/e2e/graphics/test-cases/series/no-last-price-animation-on-first-set-data-after-reseting-data.js (hunk 2 above)
Comment (kirchet) [reply tests/e2e/graphics/test-cases/series/no-last-price-animation-on-first-set-data-after-reseting-data.js:22]: In the middle

File: src/api/data-layer.ts (hunk 4 above)
Comment (kirchet) [reply src/api/data-layer.ts]: https://github.com/tradingview/lightweight-charts/pull/892/commits/7fabd9d7c16aee4573caeec1b4294cb5293171f5

File: src/api/data-layer.ts (hunk 3 above)
Comment (kirchet) [reply src/api/data-layer.ts]: https://github.com/tradingview/lightweight-charts/pull/892/commits/7fabd9d7c16aee4573caeec1b4294cb5293171f5

**Review by timocov — APPROVED** [review]
