### PR TITLE
fix timescale crosshair label during initial render

### LINKED ISSUE #1255: Crosshair label text appears on the chart during initial render
The first render of time scale, BEFORE you move your cursor over the chart, contains some artefact text drawn over a border, like on the screenshot below. Looks like the text normally drawn by CrosshairTimeAxisView 

**Lightweight Charts Version:** `master` branch

**Steps/code to reproduce:**
1. Create a chart, and don't interact with it.

Helps to change the background colour to make the text more visible

**Actual behavior:**
Crosshair text appears on the time scale (without the crosshair label background).

**Expected behavior:**
Crosshair labels shouldn't appear at all when the user hasn't interacted with the chart yet.

**Screenshots:**
crosshair_bug

### PR DESCRIPTION
**Pull request by SlicedSilver**
The text for the timescale crosshair label could appear when even if the coordinate was NaN.

**Type of PR:** bugfix

**PR checklist:**

- [x] Addresses an existing issue: fixes #1255 
- `N/A` ~Includes tests~
- `N/A` ~Documentation update~

**Overview of change:**

Crosshair label won't be rendered if the coordinate is `NaN`.

### CODE REVIEW

File: src/views/time-axis/crosshair-time-axis-view.ts [hunk 1]
```diff
@@ -62,7 +62,7 @@ export class CrosshairTimeAxisView implements ITimeAxisView {
 		data.width = timeScale.width();
 
 		const value = this._valueProvider();
-		if (!value.time) {
+		if (!value.time || Number.isNaN(value.coordinate)) {
```
Comment (kirchet) [inline src/views/time-axis/crosshair-time-axis-view.ts:65]: Minor: it's better to check for `Number.isFinite`, it checks both for `NaN` and `Infinity`

Comment (SlicedSilver) [reply src/views/time-axis/crosshair-time-axis-view.ts]: Thanks 👍

**Review by kirchet — APPROVED** [review]
