### PR TITLE
Fixed using transparent background

### LINKED ISSUE #40: backgroundColor: 'transparent' / using transparency
When setting the layout properties to transparent, the chart doesn't seem to be working correctly.
https://jsfiddle.net/70k4yuhL/2/

### PR DESCRIPTION
**Pull request by eugene-korobko**
Fixes #40

**Type of PR:** enhancement

**PR checklist:**

- [x] Addresses an existing issue: fixes #40
- [x] Includes tests - graphic tests transparent-background.js
- [ ] Documentation update

**Overview of change:**
If background color has alpha component, clear canvas before paiting the background

**Is there anything you'd like reviewers to focus on?**

### CODE REVIEW

File: tests/e2e/graphics/test-cases/initial-options/transparent-background.js [hunk 1]
```diff
@@ -0,0 +1,322 @@
...
+	var chart = LightweightCharts.createChart(container, {
+		layout: {
+			backgroundColor: 'rgba(80, 80, 80, 0.5)',
+		},
+	});
+
+	var series = chart.addLineSeries();
+
+	series.setData([
+		{ time: '2018-03-28', value: 154 },
```
Comment (timocov) [inline tests/e2e/graphics/test-cases/initial-options/transparent-background.js]: Can we use random data as other test cases?

File: tests/e2e/graphics/test-cases/initial-options/transparent-background.js [hunk 2]
```diff
@@ -0,0 +1,322 @@
...
+		{ time: '2019-06-03', value: 96.800003 },
+		{ time: '2019-06-04', value: 96.34 },
+		{ time: '2019-06-05', value: 95.94 },
+	]);
+
+	chart.timeScale().setVisibleRange({ from: 1545782400, to: 1559692800 });
+
+	return new Promise((resolve) => {
+		setTimeout(() => {
+			chart.timeScale().setVisibleRange({ from: 1538352000, to: 1545782400 });
```
Comment (timocov) [inline tests/e2e/graphics/test-cases/initial-options/transparent-background.js]: It's a copy-paste?

File: src/gui/canvas-utils.ts [hunk 3]
```diff
@@ -27,6 +28,10 @@ export function resizeCanvas(canvas: HTMLCanvasElement, newSize: Size): void {
 export function clearRect(ctx: CanvasRenderingContext2D, x: number, y: number, w: number, h: number, clearColor: string): void {
 	ctx.save();
 	ctx.translate(-0.5, -0.5);
+	const color = tryParseRgbaString(clearColor);
```
Comment (timocov) [inline src/gui/canvas-utils.ts]: Will not be here a performance issue to parse the color on every paint? Maybe we can cache the result somewhere in PaneWidget/PriceAxisWidget/TimeAxisWidget? @subzey what do you think?

Comment (timocov) [reply src/gui/canvas-utils.ts]: Or even parse there, but here take an argument with something like `forceClear` (I don't know a good name for now for that flag).

File: tests/e2e/graphics/test-cases/initial-options/transparent-background.js [hunk 4]
```diff
@@ -0,0 +1,322 @@
+// eslint-disable-next-line no-unused-vars
+function runTestCase(container) {
+	var chart = LightweightCharts.createChart(container, {
+		layout: {
+			backgroundColor: 'rgba(80, 80, 80, 0.5)',
```
Comment (timocov) [inline tests/e2e/graphics/test-cases/initial-options/transparent-background.js]: Can you please change background color of the webpage as well to see it on the screenshots?

File: tests/e2e/graphics/test-cases/initial-options/transparent-background.js (hunk 2 above)
Comment (eugene-korobko) [reply tests/e2e/graphics/test-cases/initial-options/transparent-background.js]: No, different range. We need it because drawing artefacts appear after scrolling

File: tests/e2e/graphics/test-cases/initial-options/transparent-background.js (hunk 4 above)
Comment (eugene-korobko) [reply tests/e2e/graphics/test-cases/initial-options/transparent-background.js]: The idea of the test is to show that there is no drawing artefacts after scrolling

Comment (timocov) [reply tests/e2e/graphics/test-cases/initial-options/transparent-background.js]: Yeah, I got it, but the reason of using "transparent background" is see body's (or under-chart element's) background, and it would be good to see, that these colors are mixed.

File: tests/e2e/graphics/test-cases/initial-options/transparent-background.js (hunk 2 above)
Comment (timocov) [reply tests/e2e/graphics/test-cases/initial-options/transparent-background.js]: Ah, you'r right!

File: src/gui/canvas-utils.ts (hunk 3 above)
Comment (eugene-korobko) [reply src/gui/canvas-utils.ts]: 1. Parsing is a single call of regexp, I believe it is very effective
2. Method name is "clearRect". It means it "clear rect and fill it with color". Internally, it did not clear becasue of it is not necessary if color has no alpha. However, it was just an internal optimization; calling code should know nothing about this, it just calls a function to clear rect and fill it with a color

Comment (eugene-korobko) [reply src/gui/canvas-utils.ts]: 1. Parsing is a single call of regexp, I believe it is very effective
2. Method name is "clearRect". It means it "clear rect and fill it with color". Internally, it did not clear becasue of it is not necessary if color has no alpha. However, it was just an internal optimization; calling code should know nothing about this, it just calls a function to clear rect and fill it with a color

Comment (eugene-korobko) [reply src/gui/canvas-utils.ts]: 1. Parsing is a single call of regexp, I believe it is very effective
2. Method name is "clearRect". It means it "clear rect and fill it with color". Internally, it did not clear becasue of it is not necessary if color has no alpha. However, it was just an internal optimization; calling code should know nothing about this, it just calls a function to clear rect and fill it with a color

Comment (timocov) [inline src/gui/canvas-utils.ts]: What if color is named color `transparent` (see original issue https://github.com/tradingview/lightweight-charts/issues/40#issue-453651199)? Will it work too? Would be nice to have test case for it.

Comment (subzey) [reply src/gui/canvas-utils.ts]: Regexps are not so fast. :man_shrugging:. I believe, we can benefit from caching the color.

Probably, it can be done at the `color.ts` level memoizing the color param. It can end up in creating a huge `_cache` dictionary, but as for me, it's quite improbable a lot of different colors will be used.

File: src/gui/canvas-utils.ts [hunk 5]
```diff
@@ -27,6 +28,10 @@ export function resizeCanvas(canvas: HTMLCanvasElement, newSize: Size): void {
...
+	if (color !== null && color[3] < 1) {
+		ctx.clearRect(x, y, w, h);
```
Comment (subzey) [inline src/gui/canvas-utils.ts]: Clearing the previous ctx contents and fill can be done as a single operation using [`globalCompositeOperation = 'copy'`](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/globalCompositeOperation). This mode could even be faster becuase it doesn't blend the previous data with the new one.

Demo: https://jsfiddle.net/subzey/cxej91f2/

Comment (subzey) [reply src/gui/canvas-utils.ts]: The added benefit is that we don't need to check the alpha channel, so we can skip `tryParseRgbaString` entirely!

Comment (subzey) [reply src/gui/canvas-utils.ts]: @timocov @eugene-korobko

Comment (eugene-korobko) [reply src/gui/canvas-utils.ts]: Nice idea! Will change

File: tests/e2e/graphics/test-cases/initial-options/transparent-background.js (hunk 1 above)
Comment (eugene-korobko) [reply tests/e2e/graphics/test-cases/initial-options/transparent-background.js]: done

File: src/gui/canvas-utils.ts (hunk 3 above)
Comment (eugene-korobko) [reply src/gui/canvas-utils.ts]: it is not actual now after using 'copy' compositing

File: tests/e2e/graphics/test-cases/initial-options/transparent-background.js (hunk 4 above)
Comment (eugene-korobko) [reply tests/e2e/graphics/test-cases/initial-options/transparent-background.js]: Well, master already draws transparent backround, the problem was in clearing chart elements after chart changes. Test should show difference between "before" and "after", the differece is artefacts, not transparent background

File: src/gui/canvas-utils.ts (hunk 3 above)
Comment (eugene-korobko) [reply src/gui/canvas-utils.ts]: this code has been removed

File: src/gui/canvas-utils.ts (hunk 5 above)
Comment (eugene-korobko) [reply src/gui/canvas-utils.ts]: done
