### PR TITLE
fix series crosshair marker x positioning #1504

### LINKED ISSUE #1504: Some series point markers are non-symmetric
**Lightweight Charts™ Version:** 4.1.2

**Steps/code to reproduce:**

Add a line series with `pointMarkersRadius: 8,`, hover series points, some of them are non-symmetric

**Screenshots:**

image

**CodeSandbox/JSFiddle/etc link:**

[JS Fiddle](https://jsfiddle.net/ekorobko/jxm20d6v/1/)

hover the third point

### PR DESCRIPTION
**Pull request by SlicedSilver**
**Type of PR:** bugfix

**PR checklist:**

- [x] Addresses an existing issue: fixes #1504
- [x] Includes tests
- `N/A` ~Documentation update~

**Overview of change:**
The alignment of the crosshair marker for the series didn't match the alignment of the Line series point markers. It appears that the series markers were being drawn correctly, and rather that the crosshair marker position was incorrect. The code was using MediaCoordinates without any corrections.

**Tests:**
Since the code change is to the crosshair marker, it is expected that the number of failing tests will be large for the strange DPRs like 1.25 and 1.5.

The added test `crosshair-marker-position` will only test the issue properly on the lower DPRs (`1`, `1.25`, `1.5`).

### CODE REVIEW

File: tests/e2e/graphics/test-cases/crosshair-marker-position.js [hunk 1]
```diff
@@ -0,0 +1,44 @@
+// Ignore the mouse movement because we are using setCrosshairPosition
+window.ignoreMouseMove = true;
```
Comment (eugene-korobko) [inline tests/e2e/graphics/test-cases/crosshair-marker-position.js:2]: will this set the flag forever? Does this affect other tests?

**Review by eugene-korobko — DISMISSED** [review]

**Review by eugene-korobko — APPROVED** [review]

**Review by eugene-korobko — APPROVED** [review]
