### PR TITLE
Fixed bug with wrong displaying several non regular series

### LINKED ISSUE #321: Bug while rendering few datasets with not equal timescale
**Lightweight Charts Version:** 

**First case**

I have there 3 datasets 21 timepoints each. They are not equal in time: one datasets starts from point `{"value":0,"time":"2019-11-26"}` while others starts from `{"value":0,"time":"2019-04-14"}`. But after chart rendering you can see that this datasets (orange line) starts not from 26 Nov '19 but from 10 Sep '19.

image

jsfiddle with first case: https://jsfiddle.net/pensioneer/98p0v57a/1/

**Second case**

I have modified my fiddle to be loop-based. With this approach, I expected to get more flexible configuration. I got the same unexpected behavior, but with another result. After rendering I could see that the orange line starts from 4 Apr '19. Neither from 10 Sep '19 (first case) nor from 26 Nov '19 (expected result).

image

The datasets and configuration options are the same as in the first case. Only the initialization method was changed.

jsfiddle with second case: https://jsfiddle.net/pensioneer/ac1Le3bh/9/

**Tip**
If run my jsfiddles with Lightweight Charts Version 1.0.0 (https://unpkg.com/lightweight-charts@1.0.0/dist/lightweight-charts.standalone.production.js) orange line renders as expected (from 26 Nov '19)

### PR DESCRIPTION
**Pull request by kirchet**
**Type of PR:** bugfix

**PR checklist:**

- [x] Addresses an existing issue: fixes #321
- [x] Includes tests
- [ ] Documentation update

**Overview of change:**

Fixed bug with wrong displaying several non-regular series

### CODE REVIEW

File: src/api/chart-api.ts [hunk 1]
```diff
@@ -236,7 +236,7 @@ export class ChartApi implements IChartApi, DataUpdatesConsumer<SeriesType> {
 		const timeScaleUpdate = update.timeScaleUpdate;
 		model.updateTimeScale(timeScaleUpdate.index, timeScaleUpdate.changes, timeScaleUpdate.marks, true);
 		timeScaleUpdate.seriesUpdates.forEach((value: SeriesUpdatePacket, key: Series) => {
-			key.updateData(value.update);
+			key.updateData(value.update, true);
```
Comment (timocov) [inline src/api/chart-api.ts]: Why can't we call `clearData` method here instead of passing `true`? Also, looks like we don't need to call `clearData` for the series in [`DataLayer::setSeriesData`](https://github.com/tradingview/lightweight-charts/blob/master/src/api/data-layer.ts#L261)?

Comment (kirchet) [reply src/api/chart-api.ts]: Because `clearData` clears also pallete which was filled right before in `DataLayer`

Comment (timocov) [reply src/api/chart-api.ts]: Oh crap 💩... Looks like we should fix it in https://github.com/tradingview/lightweight-charts/issues/270#issue-529280808 😂

Comment (timocov) [reply src/api/chart-api.ts]: What do you think about something like that?

```suggestion
			// the latest arg `true` must be removed in https://github.com/tradingview/lightweight-charts/issues/270
			// here we don't need to clear palettes because they were just filled in DataLayer
			// see https://github.com/tradingview/lightweight-charts/pull/330#discussion_r379415805
			key.updateData(value.update, true);
```

Comment (kirchet) [reply src/api/chart-api.ts]: Looks good
