### PR TITLE
applyOptions of histogram series with color doesn't affect the data

### LINKED ISSUE #112: applyOptions of histogram series with color doesn't affect the data
**Lightweight Charts Version:** 1.0.0

**Steps/code to reproduce:**

```javascript
var chart = LightweightCharts.createChart(document.body);

var series = chart.addHistogramSeries({
	color: 'blue',
});

series.setData([
	{ time: '2019-05-23', value: 10, color: 'red' },
	{ time: '2019-05-24', value: 20, color: 'green' },
	{ time: '2019-05-28', value: 30 },
]);

series.applyOptions({
	color: 'yellow',
});
```

**Actual behavior:**

The last histogram item is blue.

**Expected behavior:**

The last histogram item is yellow.

### PR DESCRIPTION
**Pull request by kirchet**
**Type of PR:** bugfix

**PR checklist:**

- [x] Addresses an existing issue: fixes #112 
- [x] Includes tests
- [ ] Documentation update

**Overview of change:**

Updating palette on applying options

### CODE REVIEW

File: src/model/series.ts [hunk 1]
```diff
@@ -262,6 +262,11 @@ export class Series<T extends SeriesType = SeriesType> extends PriceDataSource i
 			this._recreateFormatter();
 		}
 
+		if (this._seriesType === 'Histogram') {
+			this._palette.replaceColorByIndex((this._options as HistogramStyleOptions).color, 0);
+		}
+
+		this._recreateFormatter();
```
Comment (timocov) [inline src/model/series.ts]: It looks like it's dupe line?

File: tests/e2e/graphics/test-cases/series/histogram-change-default-color.js [hunk 2]
```diff
@@ -0,0 +1,20 @@
...
+		{ time: '2019-05-23', value: 10, color: 'red' },
+		{ time: '2019-05-24', value: 20, color: 'green' },
+		{ time: '2019-05-28', value: 30 },
+	]);
+
+	series.applyOptions({
+		color: 'orange',
+	});
+}
+
```
Comment (timocov) [inline tests/e2e/graphics/test-cases/series/histogram-change-default-color.js]:
```suggestion
```

File: src/model/series.ts [hunk 3]
```diff
@@ -262,6 +262,11 @@ export class Series<T extends SeriesType = SeriesType> extends PriceDataSource i
 			this._recreateFormatter();
 		}
 
+		if (this._seriesType === 'Histogram') {
+			this._palette.replaceColorByIndex((this._options as HistogramStyleOptions).color, 0);
```
Comment (timocov) [inline src/model/series.ts]: @eugene-korobko can you please take a look? We've 3 place in the code where knows about zero-indexed color (that it's a default one). Maybe we can do something with that?

Comment (eugene-korobko) [reply src/model/series.ts]: Lets encapsulate it in palette class with adding a "default" color?

Comment (kirchet) [reply src/model/series.ts]: I removed storing default color in palette. We can change it and store default color in pallete, but in this case it's required more code

File: src/model/palette.ts [hunk 4]
```diff
@@ -9,6 +9,13 @@ export class Palette {
 		return ensureDefined(this._indexToColor.get(index));
 	}
 
+	public replaceColorByIndex(color: string, index: number): void {
```
Comment (timocov) [inline src/model/palette.ts]: Do we still need this?

File: src/model/series.ts [hunk 5]
```diff
@@ -513,12 +513,4 @@ export class Series<T extends SeriesType = SeriesType> extends PriceDataSource i
 		const priceSource = 'close';
 		this._barFunction = barFunction(priceSource);
 	}
-
-	private _createDefaultPalette(): Palette {
-		const res = new Palette();
-		if (this._seriesType === 'Histogram') {
-			res.addColor((this._options as HistogramStyleOptions).color);
```
Comment (timocov) [inline src/model/series.ts]: It looks like we should remove generating palette from HistogramSeriesApi as well (or even remove HistogramSeriesApi because we already generate Palette in DataLayer)?

File: src/model/palette.ts (hunk 4 above)
Comment (kirchet) [reply src/model/palette.ts]: Already removed

File: src/views/pane/histogram-pane-view.ts [hunk 6]
```diff
@@ -69,11 +69,15 @@ export class SeriesHistogramPaneView extends SeriesPaneViewBase<'Histogram', Tim
...
 		this._series.bars().each((index: TimePointIndex, bar: Bar) => {
 			const value = barValueGetter(bar.value);
-			const colorIndex = bar.value[SeriesPlotIndex.Color] as number;
+			const paletteColorIndex = bar.value[SeriesPlotIndex.Color];
+
 			const item = createRawItem(index, value);
-			const color = palette.colorByIndex(colorIndex);
+			const color = paletteColorIndex != null ? palette.colorByIndex(paletteColorIndex) : defaultColor;
+			const colorIndex = paletteColorIndex == null ? 0 : paletteColorIndex + 1;
 			const data = this._paletteData[colorIndex] || createEmptyHistogramData(barSpacing, histogramStyleProps.lineWidth, color);
```
Comment (eugene-korobko) [inline src/views/pane/histogram-pane-view.ts]: Lets add comment why do we have `paletteColorIndex + 1` here
(because of index 0 means default color is suppose)

File: src/model/series.ts (hunk 5 above)
Comment (timocov) [reply src/model/series.ts]: Or just clear palette before applying the data.

Comment (kirchet) [reply src/model/series.ts]: HistogramSeriesApi is removed

File: src/views/pane/histogram-pane-view.ts (hunk 6 above)
Comment (kirchet) [reply src/views/pane/histogram-pane-view.ts]: Done
