### PR TITLE
Fixed getting index for series marker

### LINKED ISSUE #464: Incorrect alignment of markers if series has gaps
**Lightweight Charts Version:**  2.0.0 

**Steps/code to reproduce:**

```
var chart = LightweightCharts.createChart(document.body, {
	width: 600,
  height: 300,
	layout: {
		backgroundColor: '#ffffff',
		textColor: 'rgba(33, 56, 77, 1)',
	},
	grid: {
		vertLines: {
			color: 'rgba(197, 203, 206, 0.7)',
		},
		horzLines: {
			color: 'rgba(197, 203, 206, 0.7)',
		},
	},
	timeScale: {
		timeVisible: true,
    secondsVisible: false,
	},
});

var lineSeries = chart.addLineSeries();

lineSeries.setData([
	{ time: 1556877600, value: 230.12 },
	{ time: 1556881200, value: 230.24 },
	{ time: 1556884800, value: 230.63 },
	{ time: 1556888400, value: 231.35 },
	{ time: 1556892000, value: 232.24 },
	{ time: 1556895600, value: 232.52 }
]);

var lineSeries1 = chart.addLineSeries({
color: "red"
});

lineSeries1.setData([
	{ time: 1556877600, value: 130.12 },
	{ time: 1556881000, value: 130.24 },
	{ time: 1556884800, value: 130.63 },
	{ time: 1556888400, value: 131.35 },
	{ time: 1556892000, value: 132.24 },
	{ time: 1556895600, value: 132.52 }
]);

lineSeries.setMarkers([{
color: "green",
position: "inBar",
shape: "arrowDown",
time: 1556880900
}]);
chart.timeScale().fitContent();

```

**Actual behavior:**

Marker is appearing at the top of chart

**Expected behavior:**

Marker should appear in the lineSeries "inBar"

**Screenshots**

markerIssue

**CodeSandbox/JSFiddle/etc link:**

https://jsfiddle.net/sihare123/g2t0hfL6/12/

### PR DESCRIPTION
**Pull request by timocov**
**Type of PR:** bugfix

**PR checklist:**

- [x] Addresses an existing issue: fixes #464
- [x] Includes tests
- [ ] Documentation update

### CODE REVIEW

File: tests/e2e/graphics/test-cases/series-markers/marker-in-gap-from-left.js [hunk 1]
```diff
@@ -0,0 +1,40 @@
...
+		{ time: 1556892000, value: 132.24 },
+		{ time: 1556895600, value: 132.52 },
+	]);
+
+	lineSeries.setMarkers([
+		{
+			color: 'green',
+			position: 'inBar',
+			shape: 'arrowDown',
+			time: 1556877600,
```
Comment (timocov) [inline tests/e2e/graphics/test-cases/series-markers/marker-in-gap-from-left.js:35]:
```suggestion
			time: 1556870600,
```
