### PR TITLE
71: Use observer for auto resizing and hide "% 2" magic with a strategy

### LINKED ISSUE #71: Handle resize with ResizeObserver if it's exist in window
**Lightweight Charts Version:** 
Latest

**Steps/code to reproduce:**
Just rotate the device

**Actual behavior:**
Fixed width always

**Expected behavior:**
Need to be responsive

**Screenshots**
Here also: https://www.tradingview.com/lightweight-charts/

### LINKED ISSUE #367: Refactoring resize the chart
https://github.com/tradingview/lightweight-charts/blob/a1c8d55e710783766d1d55a56ff296e8d5ad5642/src/gui/chart-widget.ts#L80-L91

Here we have hidpi fixes for chart's size, but that size applies in constructor only. Thus, if we'll resize the chart, we don't apply that "magic" and can get smoothing.

### PR DESCRIPTION
**Pull request by eugene-korobko**
**Type of PR:** enhancement

**PR checklist:**

- [x] Addresses an existing issue: fixes #71, fixes #367
- [x] Includes tests
- [x] Documentation update

**Overview of change:**
- Added an option `useObserver` that makes the chart resizing automatically to fill parent's client area
- Extracted magic with keeping sizes odd to separate module and encapsulate with interface

**Is there anything you'd like reviewers to focus on?**

One graphic test has been broken because we start applying "odd magic" to explicitly defined sizes

### CODE REVIEW

File: src/model/chart-model.ts [hunk 1]
```diff
@@ -80,6 +80,11 @@ export interface ChartOptions {
 	width: number;
 	/** Height of the chart */
 	height: number;
+	/**
+	 * Use observer to resize chart to its parent client area
+	 * Calling code is responsible for providing pilyfill if native implementation is not avaibable
+	 * */
+	useObserver: boolean;
```
Comment (timocov) [inline src/model/chart-model.ts:87]: I'm not sure that `useObserver` is good name for handling resize. Maybe something like `autosize` or `handleResize`?

File: src/model/chart-model.ts [hunk 2]
```diff
@@ -80,6 +80,11 @@ export interface ChartOptions {
 	width: number;
 	/** Height of the chart */
 	height: number;
+	/**
+	 * Use observer to resize chart to its parent client area
+	 * Calling code is responsible for providing pilyfill if native implementation is not avaibable
+	 * */
```
Comment (timocov) [inline src/model/chart-model.ts:86]:
```suggestion
	 * Use ResizeObserver to handle container's resize to resize a chart automatically.
	 * Note that the library WON'T ADD own polyfill for `ResizeObserver` if it doesn't exist in the global scope. So you have to be sure that you enable this option only if a browser supports it or you provide a polyfill instead. Otherwise, a warn message will be printed and no handling resize will be applied.
	 **/
```

Maybe something like that?

Comment (timocov) [reply src/model/chart-model.ts:86]: Probably we need to update docs as well accordingly.

File: src/gui/chart-widget.ts [hunk 3]
```diff
@@ -78,29 +85,31 @@ export class ChartWidget implements IDestroyable {
...
-		if (width === 0 || height === 0) {
-			const containerRect = container.getBoundingClientRect();
-			// TODO: Fix it better
-			// on Hi-DPI CSS size * Device Pixel Ratio should be integer to avoid smoothing
-			// For chart widget we decreases because we must be inside container.
-			// For time axis this is not important, since it just affects space for pane widgets
-			if (width === 0) {
-				width = Math.floor(containerRect.width);
-				width -= width % 2;
+		if (options.useObserver) {
```
Comment (timocov) [inline src/gui/chart-widget.ts:88]: What's about enabling this option on-the-fly? I guess it might be a trick, for instance if you'd like to load polyfills async and then handle resize events.

File: src/gui/chart-widget.ts [hunk 4]
```diff
@@ -78,29 +85,31 @@ export class ChartWidget implements IDestroyable {
...
+			// eslint-disable-next-line no-restricted-syntax
+			if (!('ResizeObserver' in window)) {
+				warn('Options contains "useObserver" flag, but the browser does not support this');
```
Comment (timocov) [inline src/gui/chart-widget.ts:91]: > the browser does not support this

I think we need to write a bit more about that. Doesn't support what?

File: src/gui/chart-widget.ts [hunk 5]
```diff
@@ -78,29 +85,31 @@ export class ChartWidget implements IDestroyable {
...
+			} else {
+				this._observer = new ResizeObserver((entries: ResizeObserverEntry[]) => {
+					const containerEntry = entries.find((entry: ResizeObserverEntry) => entry.target === container);
+					if (!containerEntry || !containerEntry.devicePixelContentBoxSize) {
```
Comment (timocov) [inline src/gui/chart-widget.ts:95]: `containerEntry.devicePixelContentBoxSize` Do we need to check it here, even if we don't use it anywhere?

File: src/gui/chart-widget.ts [hunk 6]
```diff
@@ -78,29 +85,31 @@ export class ChartWidget implements IDestroyable {
...
+					this.resize(containerEntry.contentRect.width, containerEntry.contentRect.height);
+				});
+				this._observer.observe(container, { box: 'border-box' });
 			}
-
-			if (height === 0) {
-				height = Math.floor(containerRect.height);
-				height -= height % 2;
+		} else {
+			let size = new Size(this._options.width, this._options.height);
```
Comment (timocov) [inline src/gui/chart-widget.ts:103]: do we actually need to create this `Size` variable? Can't we use 2 `number` variables? 🤔

File: src/gui/chart-widget.ts [hunk 7]
```diff
@@ -78,29 +85,31 @@ export class ChartWidget implements IDestroyable {
...
+				const containerRect = container.getBoundingClientRect();
+				size = new Size(containerRect.width, containerRect.height);
 			}
-		}
 
-		// BEWARE: resize must be called BEFORE _syncGuiWithModel (in constructor only)
-		// or after but with adjustSize to properly update time scale
-		this.resize(width, height);
+			// BEWARE: resize must be called BEFORE _syncGuiWithModel (in constructor only)
+			// or after but with adjustSize to properly update time scale
```
Comment (timocov) [inline src/gui/chart-widget.ts:110]: is it comment important while using `ResizeObserver`? Will a `callback` be called async?

File: src/gui/internal-layout-sizes-hints.ts [hunk 8]
```diff
@@ -0,0 +1,40 @@
+import { Size } from './canvas-utils';
+
+export interface InternalLayoutSizeHints {
```
Comment (timocov) [inline src/gui/internal-layout-sizes-hints.ts:3]: What does "internal" here mean? is it inner? or something else?

File: src/gui/internal-layout-sizes-hints.ts [hunk 9]
```diff
@@ -0,0 +1,40 @@
...
+	public suggestTimeScaleHeight(originalHeight: number): number {
+		return originalHeight + originalHeight % 2;
+	}
+
+	public suggestPriceScaleWidth(originalWidth: number): number {
+		return originalWidth + originalWidth % 2;
+	}
+}
+
+export class InternalLayoutSizeHintsKeepIriginal implements InternalLayoutSizeHints {
```
Comment (timocov) [inline src/gui/internal-layout-sizes-hints.ts:30]: Is it used anywhere?

**Review by timocov — CHANGES_REQUESTED** [review]

File: src/model/chart-model.ts (hunk 1 above)
Comment (eugene-korobko) [reply src/model/chart-model.ts:87]: fitContent?

Comment (timocov) [reply src/model/chart-model.ts:87]: Nah, we already have that (method, but anyway) 😂 I think we might to look at others libraries, probably they already have this.

File: src/gui/chart-widget.ts (hunk 7 above)
Comment (eugene-korobko) [reply src/gui/chart-widget.ts:110]: Yes, I think so. Call from observer callback is the same as external resize call

File: src/gui/internal-layout-sizes-hints.ts (hunk 8 above)
Comment (eugene-korobko) [reply src/gui/internal-layout-sizes-hints.ts:3]: This means this hints relate to internal chart layout - panes/scales/etc

File: src/gui/internal-layout-sizes-hints.ts (hunk 9 above)
Comment (eugene-korobko) [reply src/gui/internal-layout-sizes-hints.ts:30]: no, it is just to allow easy disabling of %2 magic...
And I have a Typo here...

Comment (timocov) [reply src/gui/internal-layout-sizes-hints.ts:30]: > no, it is just to allow easy disabling of %2 magic...

easy for whom? if it isn't used anywhere, it looks like deadcode, which will be removed from the bundle and you can't access it anyway (or even apply it somehow) 🤔

File: src/gui/chart-widget.ts (hunk 7 above)
Comment (timocov) [reply src/gui/chart-widget.ts:110]: Don't we need to do a first resize in the widget constructor to have an initial size? I guess we should test it

File: src/model/chart-model.ts (hunk 1 above)
Comment (eugene-korobko) [reply src/model/chart-model.ts:90]: Well, will rename to autoSize
If anyboydy has better name - speak now or forever hold your peace )

File: src/gui/chart-widget.ts (hunk 7 above)
Comment (eugene-korobko) [reply src/gui/chart-widget.ts]: Yes.
ResizeObserver fires the first event immediately not for all the cases, so we have to set initial size with both cases

File: src/gui/internal-layout-sizes-hints.ts (hunk 9 above)
Comment (eugene-korobko) [reply src/gui/internal-layout-sizes-hints.ts]: ok

File: docs/customization.md [hunk 10]
```diff
@@ -21,6 +21,28 @@ If you want the chart size to be adjusted when the web page is resized, use the
...
+
+Please pay your attention that `userObserver` option and explicit sizes options `width` and `height` conflict one with others.
+If you specify `userObserver` flag, `width` and `height` options will be ignored in common case
+and could only be used as fallback if using `ResizeObserver` has failed.
+
+The flag `userObserver` could also be set with and unset with `applyOptions` function.
+
+```js
+const chart = LightweightCharts.createChart(document.body, {
+    useObserver: true,
```
Comment (timocov) [inline docs/customization.md:42]:
```suggestion
### Auto Size

Setting `autoSize` flag to `true` makes chart monitoring container and changing its size on every container resize.

This feature requires [`ResizeObserver`](https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserver) class to be available in the global scope.

Note that calling code is responsible for providing a polyfill if required. If the global scope does not have `ResizeObserver`, a warning will appear and the flag will be ignored.

Please pay your attention that `autoSize` option and explicit sizes options `width` and `height` conflict one with others.

If you specify `autoSize` flag, `width` and `height` options will be ignored in common case and could only be used as fallback if using `ResizeObserver` has failed.

The flag `autoSize` could also be set with and unset with `applyOptions` function.

```js
const chart = LightweightCharts.createChart(document.body, {
    autoSize: true,
```

File: src/gui/chart-widget.ts [hunk 11]
```diff
@@ -52,8 +56,14 @@ export class ChartWidget implements IDestroyable {
 	private _clicked: Delegate<MouseEventParamsImplSupplier> = new Delegate();
 	private _crosshairMoved: Delegate<MouseEventParamsImplSupplier> = new Delegate();
 	private _onWheelBound: (event: WheelEvent) => void;
+	private _observer: ResizeObserver | null = null;
+	// replace InternalLayoutSizeHintsKeepOdd with InternalLayoutSizeHintsKeepOriginal to turn "odd magic" off
```
Comment (timocov) [inline src/gui/chart-widget.ts:60]:
```suggestion
```

File: src/gui/chart-widget.ts [hunk 12]
```diff
@@ -199,6 +207,14 @@ export class ChartWidget implements IDestroyable {
 		const height = options.height || this._height;
 
 		this.resize(width, height);
+
+		if (options.autoSize && !this._observer) {
+			// installing observer will override resize if successfull
+			this._installObserver();
+		}
+		if (options.autoSize === false && this._observer) {
```
Comment (timocov) [inline src/gui/chart-widget.ts:215]:
```suggestion
		if (options.autoSize && this._observer === null) {
			// installing observer will override resize if successful
			this._installObserver();
		}

		if (!options.autoSize && this._observer !== null) {
```

File: src/gui/chart-widget.ts [hunk 13]
```diff
@@ -199,6 +207,14 @@ export class ChartWidget implements IDestroyable {
 		const height = options.height || this._height;
 
 		this.resize(width, height);
```
Comment (timocov) [inline src/gui/chart-widget.ts:209]: Shouldn't explicit resize disable autoSize?

File: src/model/chart-model.ts [hunk 14]
```diff
@@ -80,6 +80,14 @@ export interface ChartOptions {
 	width: number;
 	/** Height of the chart */
 	height: number;
+	/**
+	 * Settings this flag to true makes chart monitoring container
+	 * and changing its size on every container resize
+	 * This feature requires `ResizeObserver` class to be avaiable in the global scope
+	 * Calling code is responsibe for providing a polyfill if requried
+	 * If the global scope does not contain `ResizeObserver` object, a warning will appear the the flag will be ignored
```
Comment (timocov) [inline src/model/chart-model.ts:88]:
```suggestion
	 * Setting this flag to `true` makes chart monitoring container and changing its size on every container resize.
	 * This feature requires [`ResizeObserver`](https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserver) class to be available in the global scope.
	 * Note that calling code is responsible for providing a polyfill if required. If the global scope does not have `ResizeObserver`, a warning will appear and the flag will be ignored.
	 * Please pay your attention that `autoSize` option and explicit sizes options `width` and `height` conflict one with others.
	 * If you specify `autoSize` flag, `width` and `height` options will be ignored in common case and could only be used as fallback if using `ResizeObserver` has failed.
	 * The flag `autoSize` could also be set with and unset with `applyOptions` function.
```

_(or whatever will be in the docs)_

File: tests/e2e/graphics/test-cases/initial-options/use-observer.js [hunk 15]
```diff
@@ -0,0 +1,47 @@
...
+
+		box.style.position = 'absolute';
+		box.style.top = `${i * 25}%`;
+		box.style.left = 0;
+		box.style.right = 0;
+		box.style.height = '25%';
+
+		container.appendChild(box);
+
+		const chart = LightweightCharts.createChart(box, { useObserver: true, ...config });
```
Comment (timocov) [inline tests/e2e/graphics/test-cases/initial-options/use-observer.js:30]:
```suggestion
		const chart = LightweightCharts.createChart(box, { autoSize: true, ...config });
```

**Review by timocov — CHANGES_REQUESTED** [review]
It seems there is some typos here

File: src/gui/chart-widget.ts (hunk 13 above)
Comment (eugene-korobko) [reply src/gui/chart-widget.ts]: probably yes, I've changed the logic a bit

**Comment by adgower** [comment]
I pulled this branch ran npm install then npm run build:prod I could not get autoSize to work? Any tips? @eugene-korobko

**Comment by adgower** [comment]
@eugene-korobko This works great!

**Comment by SlicedSilver** [comment]
It is expected that the graphics tests will have a single failing test for `use-observer` as this is a new test specific for this feature.

**Comment by SlicedSilver** [comment]
@eugene-korobko I've made a few changes so that this PR could be merged. Could you please review if you are happy with the changes.
@Nipheris This PR makes some minor changes to the `% 2` magic code. Could you please check if you are happy with these changes as a temporary measure until we can implement `fancy-canvas` perfectly.

File: src/model/chart-model.ts [hunk 16]
```diff
@@ -247,6 +247,24 @@ export interface ChartOptions {
 	 */
 	height: number;
 
+	/**
+	 * Setting this flag to `true` will make the chart watch the chart container's size and automatically resize the chart to fit it's container whenever the size changes.
```
Comment (romfrancois) [inline src/model/chart-model.ts:251]: typo - it's container => its container

File: src/model/chart-model.ts [hunk 17]
```diff
@@ -247,6 +247,24 @@ export interface ChartOptions {
...
+	 *
+	 * This feature requires [`ResizeObserver`](https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserver) class to be available in the global scope.
+	 * Note that calling code is responsible for providing a polyfill if required. If the global scope does not have `ResizeObserver`, a warning will appear and the flag will be ignored.
+	 *
+	 * Please pay your attention that `autoSize` option and explicit sizes options `width` and `height` don't conflict with one another.
```
Comment (romfrancois) [inline src/model/chart-model.ts:256]: ~~your~~

File: src/gui/internal-layout-sizes-hints.ts [hunk 18]
```diff
@@ -0,0 +1,20 @@
+import { Size, size } from 'fancy-canvas';
+
+// on Hi-DPI CSS size * Device Pixel Ratio should be integer to avoid smoothing
+// For chart widget we decreases because we must be inside container.
```
Comment (romfrancois) [inline src/gui/internal-layout-sizes-hints.ts:4]: decrease~~s~~

**Review by romfrancois — COMMENTED** [review]
Very minor typos

**Comment by SlicedSilver** [comment]
@romfrancois Fixed the typos 👍

**Review by romfrancois — APPROVED** [review]
