### PR TITLE
Don't extend range by 0.5 in Series (it's already done in PriceScale)

### LINKED ISSUE #122: Price Axis Scaling Bug
It appears there's an intermittent, but repeatable issue with price axis scaling.

Renders correctly
https://www.chartex.pro/chartviewerstatic-debug.html?symbol=BINANCE:ALGO/USDT&trendlines=1&supports=1&timeframe=60&w=1600&h=800&barstoshow=500

Screenshot 2019-07-12 at 00 33 03

Axis scaling fails
https://www.chartex.pro/chartviewerstatic-debug.html?symbol=OANDA:EUR/GBP&trendlines=1&supports=1&timeframe=60&w=1600&h=800&barstoshow=500

### PR DESCRIPTION
**Pull request by timocov**
**Type of PR:** bugfix

**PR checklist:**

- [x] Addresses an existing issue: fixes #122
- [x] Includes tests
- [ ] Documentation update

**Overview of change:**

We don't need to extend price range by 0.5 in series because 1) it affects result price range where are other series 2) 0.5 value can be huge for current series (for example if values are about 1.0) 3) the same thing are already done in PriceScale and this is the only good place for that.

### CODE REVIEW

File: src/model/price-scale.ts [hunk 1]
```diff
@@ -857,7 +857,7 @@ export class PriceScale {
 			}
 		}
 
-		if (priceRange) {
+		if (priceRange !== null) {
 			// keep current range is new is empty
 			if (priceRange.minValue() === priceRange.maxValue()) {
 				priceRange = new PriceRange(priceRange.minValue() - 0.5, priceRange.maxValue() + 0.5);
```
Comment (timocov) [inline src/model/price-scale.ts]: After discussing with @eugene-korobko we decide that here should be 5 min ticks, not just 0.5.
