### PR TITLE
fix: marker positioning

### LINKED ISSUE #1382: Histogram has some space below bars when markers are added
**Lightweight Charts™ Version:** 4.0.1

**Steps/code to reproduce:**

Add histogram to the chart, set priceScaleId: '', add markers to the histogram series

**Actual behavior:**

Some space appears below the histogram

**Expected behavior:**

No space between histogram and bottom of the chart

**Screenshots:**

image

**CodeSandbox/JSFiddle/etc link:**
https://jsfiddle.net/exuqzLh5/

### PR DESCRIPTION
**Pull request by illetid**
**Type of PR:**  bugfix, enhancement

**PR checklist:**

- [x] Addresses an existing issue: fixes #1382
- [x] Includes tests
- [ ] Documentation update

**Overview of change:**
Fixed an issue where `marginBelow` wasn't applied. Added an enhancement that fixes #1382: When a series has only one type of markers, we apply only one margin, i.e. for markers with `position: "aboveBar"` we remove bottom margin and vice versa.

**Is there anything you'd like reviewers to focus on?**

### CODE REVIEW

File: src/views/pane/series-markers-pane-view.ts [hunk 1]
```diff
@@ -149,6 +151,14 @@ export class SeriesMarkersPaneView implements IUpdatablePaneView {
 
 		return this._autoScaleMargins;
 	}
+	protected _hasAllMarkerSamePosition(): string|null {
```
Comment (SlicedSilver) [inline src/views/pane/series-markers-pane-view.ts:154]: This method will be evaluated on every chart render (such as during scrolling, zooming, and all other actions). Since it will be evaluated so often and it's result would only ever change if `setMarkers` is used to change the markers → I think we could try to memo the function for performance reasons. It should be fine to only invalidate the result when `setMarkers` is used on the series.

**Comment by SlicedSilver** [comment]
We should also have a look at the e2e graphics test cases. I think there are more tests failing than expected such as the tests which have markers positioned above, and below.

**Review by SlicedSilver — APPROVED** [review]
LGTM 👍

File: src/views/pane/series-markers-pane-view.ts [hunk 2]
```diff
@@ -131,14 +131,16 @@ export class SeriesMarkersPaneView implements IUpdatablePaneView {
...
 				const barSpacing = this._model.timeScale().barSpacing();
 				const shapeMargin = calculateShapeMargin(barSpacing);
 				const marginsAboveAndBelow = calculateShapeHeight(barSpacing) * 1.5 + shapeMargin * 2;
+				const position = this._hasAllMarkerSamePosition();
+
 				this._autoScaleMargins = {
-					above: marginsAboveAndBelow as Coordinate,
-					below: marginsAboveAndBelow as Coordinate,
+					above: position === 'belowBar' ? 0 : marginsAboveAndBelow,
+					below: position === 'aboveBar' ? 0 : marginsAboveAndBelow,
```
Comment (kirchet) [inline src/views/pane/series-markers-pane-view.ts:143]: The condition looks not correct, we should not add margins in case when position is `'inBar'`

File: src/views/pane/series-markers-pane-view.ts [hunk 3]
```diff
@@ -131,14 +131,16 @@ export class SeriesMarkersPaneView implements IUpdatablePaneView {
 	}
 
 	public autoScaleMargins(): AutoScaleMargins | null {
-		if (this._autoScaleMarginsInvalidated) {
+		if (this._autoScaleMarginsInvalidated && this._dataInvalidated) {
```
[the remark this answers is not in the document]
Comment (SlicedSilver) [reply src/views/pane/series-markers-pane-view.ts:134]: Apologies, my mistake for mentioning to try run the calculation less often at that point.
We can instead limit the `_dataInvalidated` check to only the `_hasAllMarkerSamePosition()` method because that doesn't rely on barSpacing.

File: src/views/pane/series-markers-pane-view.ts (hunk 2 above)
Comment (kirchet) [reply src/views/pane/series-markers-pane-view.ts:143]: yes, you're right

File: src/views/pane/series-markers-pane-view.ts (hunk 3 above)
[the remark this answers is not in the document]
Comment (kirchet) [reply src/views/pane/series-markers-pane-view.ts:134]: Yes we can, but we need to add one additional flag like `_hasAllMarkerSamePositionInvalidated` and use it in `_hasAllMarkerSamePosition` or update cached value in `_makeValid`
