### PR TITLE
220: Fixed step line

### LINKED ISSUE #220: `lineType` option does not work for area/line series
Does the project currently support step line charts? 
I noticed in the documentation that there is a [LineType ](https://github.com/tradingview/lightweight-charts/blob/master/docs/constants.md#linetype) enum which has an option named `WithSteps` but I cannot seem to use it in an example. Is anyone able to shed some light on this? 

Example of a line chart below.
image

### PR DESCRIPTION
**Pull request by eugene-korobko**
**Type of PR:** bugfix

**PR checklist:**

- [x] Addresses an existing issue: fixes #220
- [x] Includes tests
- [ ] Documentation update

**Overview of change:**

Fixed drawing of step lines

### CODE REVIEW

File: tests/e2e/graphics/test-cases/series/area-step-line.js [hunk 1]
```diff
@@ -0,0 +1,24 @@
...
+	}
+	return res;
+}
+
+// eslint-disable-next-line no-unused-vars
+function runTestCase(container) {
+	var chart = LightweightCharts.createChart(container);
+
+	var mainSeries = chart.addAreaSeries({
+		lineType: 1,
```
Comment (timocov) [inline tests/e2e/graphics/test-cases/series/area-step-line.js]:
```suggestion
		lineType: LightweightCharts.LineType.WithSteps,
```

File: tests/e2e/graphics/test-cases/series/step-line.js [hunk 2]
```diff
@@ -0,0 +1,26 @@
...
+	return res;
+}
+
+// eslint-disable-next-line no-unused-vars
+function runTestCase(container) {
+	var chart = LightweightCharts.createChart(container);
+
+	var mainSeries = chart.addLineSeries({
+		lineWidth: 1,
+		lineType: 1,
```
Comment (timocov) [inline tests/e2e/graphics/test-cases/series/step-line.js]:
```suggestion
		lineType: LightweightCharts.LineType.WithSteps,
```
