### PR TITLE
don't shift chart when new data replaces existing whitespace

### LINKED ISSUE #1201: Chart with whitespaces shifts on realtime
**Lightweight Charts Version:** 4.0.0

**Steps/code to reproduce:**

Open attached sample, wait for 6 seconds

**Actual behavior:**

red series shifts to the left

**Expected behavior:**

res series should keep its place

Additionally:

if replace whitespaces with some values

### PR DESCRIPTION
**Pull request by SlicedSilver**
**Type of PR:** bugfix

**PR checklist:**

- [x] Addresses an existing issue: fixes #1201
- [x] Includes tests
- [x] Documentation update

**Overview of change:**
When a realtime update is for a time point which already exists on the time scale then we won't shift the visible range of the chart anymore.

**Pipeline Checks:**
- Changes to DTS are expected. ✅
- Changes to Graphics Tests are expected (new test `do-not-shift-range-when-replacing-whitespace` was added). ✅
- It is expected that the `histogram-add-new-color-on-update` and `whitespace-updates` tests will fail. They have been manually checked and the old behaviour was incorrect. ✅

### CODE REVIEW

File: src/model/time-scale.ts [hunk 1]
```diff
@@ -153,6 +153,16 @@ export interface HorzScaleOptions {
...
 
+	/**
+	 * Should shift the visible range to the right (into the future) by the number of new bars when new data is added IF
+	 * that data is placed on existing whitespace data points (times).
+	 *
+	 * {@link shiftVisibleRangeOnNewBar} needs to be enabled for this to have any effect.
+	 *
+	 * @defaultValue `true`
+	 */
+	shiftVisibleRangeWhenNewBarReplacesWhitespace: boolean;
```
Comment (eugene-korobko) [inline src/model/time-scale.ts:164]: Do we really need this option? It is difficult to imagine why somebody needs this shifting

Comment (eugene-korobko) [reply src/model/time-scale.ts:164]: Well, from my point of view, old behavior is an obvious bug and we needn't keep back compatibility.
Formally, all bug fixes are "breaking changes" since they change the behavior, however we do not provide options to keep old behavior.
So, I'd like to select case #2.

What do you think?

Comment (SlicedSilver) [reply src/model/time-scale.ts:164]: Sounds good 👍

**Review by eugene-korobko — APPROVED** [review]
