### PR TITLE
Fix marker rendering problems with an inverted price scale

### LINKED ISSUE #1943: Incorrect marker positions on OHLC data when inverting the price scale
**Lightweight Charts™ Version:** 

**Steps/code to reproduce:**

<details>
<summary>Code</summary>

`index.ts`

```js
import {
	CandlestickSeries,
	ChartOptions,
	createChart,
	createSeriesMarkers,
	DeepPartial,
	SeriesMarker,
} from "lightweight-charts";

const chartOptions = {
	autoSize: true,
} satisfies DeepPartial<ChartOptions>;

const chart = createChart('container', chartOptions);

const candlestickSeries = chart.addSeries(CandlestickSeries, {
	upColor: "#26a69a",
	downColor: "#ef5350",
	borderVisible: false,
	wickUpColor: "#26a69a",
	wickDownColor: "#ef5350",
});

const data = [
	{ time: "2018-12-22", open: 75.16, high: 82.84, low: 36.16, close: 45.72 },
	{ time: "2018-12-23", open: 45.12, high: 53.9, low: 45.12, close: 48.09 },
	{ time: "2018-12-24", open: 60.71, high: 60.71, low: 53.39, close: 59.29 },
	{ time: "2018-12-25", open: 68.26, high: 68.26, low: 59.04, close: 60.5 },
	{ time: "2018-12-26", open: 67.71, high: 105.85, low: 66.67, close: 101.04 },
	{ time: "2018-12-27", open: 91.04, high: 121.4, low: 82.7, close: 111.4 },
	{
		time: "2018-12-28",
		open: 111.51,
		high: 142.83,
		low: 103.34,
		close: 131.25,
	},
	{ time: "2018-12-29", open: 131.33, high: 151.17, low: 77.68, close: 96.43 },
	{ time: "2018-12-30", open: 106.33, high: 110.2, low: 90.39, close: 98.1 },
	{ time: "2018-12-31", open: 109.87, high: 114.69, low: 85.66, close: 111.26 },
];

let index = -1;

candlestickSeries.setData(data.slice(0, index));

chart.timeScale().fitContent();

const markers: SeriesMarker<string>[] = [
	{
		time: data[4].time,
		position: "belowBar",
		shape: "arrowUp",
		color: "red",
	},
	{
		time: data[4].time,
		position: "aboveBar",
		shape: "arrowDown",
		color: "red",
	},
];

const seriesMarkers = createSeriesMarkers(candlestickSeries, markers);

const invert = document.getElementById("invert")!;

invert.addEventListener("click", () => {
	const inverted = !chart.options().rightPriceScale.invertScale;

	for (const marker of markers) {
		marker.position = marker.position === "aboveBar" ? "belowBar" : "aboveBar";
		marker.shape = marker.shape === "arrowUp" ? "arrowDown" : "arrowUp";
	}

	seriesMarkers.setMarkers(markers);

	chart.applyOptions({
		rightPriceScale: {
			invertScale: inverted,
		},
	});
});
```

`index.html`

```html
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  </head>
  <body style="padding: 0; margin: 0">
    <button id="invert">Invert</button>
    <div id="container" style="position: absolute; width: 100%; height: 90%"></div>
    <script type="module" src="index.ts"></script>
  </body>
</html>
```

</details>

**Actual behavior:**

The markers do not take into account when the price scale has been inverted. Examples:

1. The first image shows one marker above a candlestick, without inverting the price scale. The second image shows the inverted price scale rendering:

Image

Image

2. The first image shows one marker above a candlestick and another below the same candlestick, without inverting the price scale. The second image shows the inverted price scale rendering:

Image

Image

**Expected behavior:**

I would expect the arrows to be completely inverted (i.e. using the candle high for `aboveBar`, regardless of whether the price scale is inverted or normal).

So for (1) above, I would expected to see the following when inverted:

Image

And for (2) above, I would expect to see pretty much the same as the non-inverted price scale view:

Image

I do have [a fix for this](https://github.com/tradingview/lightweight-charts/compare/master...tpunt:lightweight-charts:inverted-chart-marker-bug), assuming that my expectations above are correct, where I can submit a PR for this with the necessary testing.

### PR DESCRIPTION
**Pull request by tpunt**
**Type of PR:** bugfix

**PR checklist:**

- [x] Addresses an existing issue: fixes #1943
- [x] Includes tests
- [ ] Documentation update

**Overview of change:**

As discussed, this fixes markers being placed in incorrect positions when the price scale is inverted. I'm happy to include the `autoInvertMarkers` option if there's desire to have it.

**Is there anything you'd like reviewers to focus on?**

I'm not sure I'm doing testing correctly. I checked out the `master` branch, built it, then renamed `dist` to `dist-golden`. Then I checked out my branch to fix the problem, built it, then executed the following:
```
npx esno ./tests/e2e/graphics/runner.ts ./dist-golden/lightweight-charts.standalone.development.js ./dist/lightweight-charts.standalone.development.js --grep "series-markers-inverted"
```

The test passed. I tried modifying the golden development file to make the test fail (i.e. include my fixes, but invert the `isInverted` condition), but the test still passes. The output is:
```
% npx esno ./tests/e2e/graphics/runner.ts ./dist-golden/lightweight-charts.standalone.development.js ./dist/lightweight-charts.standalone.development.js --grep "series-markers-inverted"
filesToServeLocally {
  'golden.js': '/Users/tpunt/lightweight-charts/dist-golden/lightweight-charts.standalone.development.js',
  'test.js': '/Users/tpunt/lightweight-charts/dist/lightweight-charts.standalone.development.js'
}
Running a server on localhost:34567 to serve 2 local file(s)
▶ Graphics tests with devicePixelRatio=1.00 (development mode)
  ▶ series-markers
    ✔ series-markers-inverted (2659.133625ms)
  ▶ series-markers (2659.84275ms)

▶ Graphics tests with devicePixelRatio=1.00 (development mode) (2724.166917ms)

Stopping server...

ℹ Duration: 7.327s
```

Not sure what I'm doing wrong here. I didn't really find the documentation too clear when it came to E2E graphics testing.

### CODE REVIEW

**Comment by tpunt** [comment]
I see what is happening now - the test data was simply copied from `series-markers-all-above.js`, but it is no good for my test case. I've applied my own data now, and can see the test failing now.

File: tests/e2e/graphics/test-cases/series-markers/series-markers-inverted.js [hunk 1]
```diff
@@ -0,0 +1,34 @@
+function runTestCase(container) {
+	const chart = window.chart = LightweightCharts.createChart(container, { layout: { attributionLogo: false } });
+
+	const mainSeries = chart.addSeries(LightweightCharts.HistogramSeries);
```
Comment (SlicedSilver) [inline tests/e2e/graphics/test-cases/series-markers/series-markers-inverted.js:4]:
```suggestion
	const mainSeries = chart.addSeries(LightweightCharts.CandlestickSeries);
```

**Comment by SlicedSilver** [comment]
The test looks correct now (failing which is expected and the screenshots are different).

File: tests/e2e/graphics/test-cases/series-markers/series-markers-inverted.js [hunk 2]
```diff
@@ -0,0 +1,34 @@
...
+		markers
+	);
+
+	chart.applyOptions({
+		rightPriceScale: {
+			invertScale: true,
+		},
+	});
+
+	markerSeries.setMarkers(markers);
```
Comment (SlicedSilver) [inline tests/e2e/graphics/test-cases/series-markers/series-markers-inverted.js:33]: Lets add one more tweak:

```suggestion
	markerSeries.setMarkers(markers);
	chart.timeScale().fitContent();
```

**Comment by tpunt** [comment]
The test is failing, but I can confirm the new output looks good.

Old test output:

image

New test output:

image
